ha_score_map = ["homeScore", "awayScore"]
ha_val_map = ["homeValue", "awayValue"]
ha_tot_map = ["homeTotal", "awayTotal"]
key_map = [
    "ballPossession",
    "yellowCards",
    "redCards",
    "fouls",
    "cornerKicks",
    "freeKicks",
    "shotsTotal",
    "shotsOnGoal",
    "shotsOffGoal",
    "totalShotsInsideBox",
    "totalShotsOutsideBox",
    "blockedScoringAttempt",
    "hitWoodwork",
    "expectedGoals",
    "bigChanceScored",
    "bigChanceMissed",
    "touchesInOppBox",
    "fouledFinalThird",
    "offsides",
    "accuratePasses",
    "throwIns",
    "finalThirdEntries",
    "dispossessed",
    "wonTacklePercent",
    "totalTackle",
    "interceptions",
    "ballRecovery",
    "totalClearance",
    "errorsLeadToShot",
    "errorsLeadToGoal",
    "goalkeeperSaves",
    "goalsPrevented",
    "highClaims",
    "punches",
    "goalKicks",
]
doubled_key_map = [
    "finalThirdPhaseStatistic",
    "accurateLongBalls",
    "accurateCross",
    "aerialDuelsPercentage",
    "groundDuelsPercentage",
    "dribblesPercentage",
]
